#!/usr/bin/env python3
"""
codebook_gen.py
===============
Offline host-side script to solve the 1D Max-Lloyd (k-means) quantization
problem for the Beta(d/2-1/2, d/2-1/2) coordinate distribution arising from
WHT rotation of unit-sphere vectors.

Outputs:
  include/codebooks.h   — C header with codebook arrays for use in TT-Metalium
                          device kernels.
  codebook_tables.npz   — NumPy archive for use by Python test harnesses.

Usage:
  python codebook_gen.py [--d 64 128 256] [--b 2 4 8] [--out-dir include]

The generated C header defines:
  const float CODEBOOK_CENTROIDS_b{b}_d{d}[{2^b}]
  const float CODEBOOK_BOUNDARIES_b{b}_d{d}[{2^b - 1}]
"""

import argparse
import os
import sys
from pathlib import Path
from typing import List

import numpy as np

# Add reference dir to path so we can import turboquant.py
sys.path.insert(0, str(Path(__file__).parent / "reference"))
from turboquant import build_codebook, Codebook  # noqa: E402


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(description="Generate TurboQuant codebooks")
    parser.add_argument(
        "--d", nargs="+", type=int, default=[64, 128, 256],
        help="Head dimensions to generate codebooks for (default: 64 128 256)"
    )
    parser.add_argument(
        "--b", nargs="+", type=int, default=[2, 4, 8],
        help="Bit-widths to generate codebooks for (default: 2 4 8)"
    )
    parser.add_argument(
        "--out-dir", type=str, default="include",
        help="Output directory for C headers (default: include)"
    )
    parser.add_argument(
        "--n-samples", type=int, default=500_000,
        help="Number of Monte Carlo samples for Max-Lloyd (default: 500000)"
    )
    parser.add_argument(
        "--validate", action="store_true",
        help="Run validation checks after generation"
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# C header generation
# ---------------------------------------------------------------------------

HEADER_TEMPLATE = """\
/**
 * codebooks.h — Auto-generated by codebook_gen.py
 * DO NOT EDIT MANUALLY.
 *
 * Max-Lloyd optimal codebooks for TurboQuant PolarQuant stage.
 * Distribution: coordinate of WHT(D*x) for unit-sphere x in R^d.
 *
 * Generated with {n_samples} Monte Carlo samples per codebook.
 *
 * Usage in TT-Metalium kernels:
 *   #include "codebooks.h"
 *   const float* cb = CODEBOOK_CENTROIDS_b4_d128;
 *   const float* bd = CODEBOOK_BOUNDARIES_b4_d128;
 *
 * Codebook index layout: centroids[0] is the most negative level.
 * Binary search on boundaries[] gives the quantization index.
 */

#pragma once

#ifdef __cplusplus
extern "C" {{
#endif

{body}

/**
 * Helper macro: select centroids/boundaries by (b, d) at compile time.
 * Example: TURBO_CENTROIDS(4, 128) expands to CODEBOOK_CENTROIDS_b4_d128
 */
#define TURBO_CENTROIDS(b, d)   CODEBOOK_CENTROIDS_b##b##_d##d
#define TURBO_BOUNDARIES(b, d)  CODEBOOK_BOUNDARIES_b##b##_d##d
#define TURBO_N_LEVELS(b)       (1 << (b))

#ifdef __cplusplus
}}
#endif
"""

SECTION_TEMPLATE = """\
/* ---- b={b}, d={d}: {n_levels} levels ---- */
static const float CODEBOOK_CENTROIDS_b{b}_d{d}[{n_levels}] = {{
{centroids_str}
}};
static const float CODEBOOK_BOUNDARIES_b{b}_d{d}[{n_bounds}] = {{
{boundaries_str}
}};
"""


def _format_array(arr: np.ndarray, per_line: int = 8) -> str:
    """Format a float array as C initializer list."""
    lines = []
    for start in range(0, len(arr), per_line):
        chunk = arr[start:start + per_line]
        lines.append("    " + ", ".join(f"{v:.10f}f" for v in chunk))
    return ",\n".join(lines)


def generate_header(
    codebooks: dict,  # {(b, d): Codebook}
    n_samples: int,
) -> str:
    sections = []
    for (b, d), cb in sorted(codebooks.items()):
        n_levels = 2 ** b
        sections.append(SECTION_TEMPLATE.format(
            b=b, d=d,
            n_levels=n_levels,
            n_bounds=n_levels - 1,
            centroids_str=_format_array(cb.centroids),
            boundaries_str=_format_array(cb.boundaries),
        ))
    body = "\n".join(sections)
    return HEADER_TEMPLATE.format(body=body, n_samples=n_samples)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_codebook(cb: Codebook, b: int, d: int, n_val: int = 100_000):
    """
    Check:
    1. Centroids are sorted and within expected range.
    2. Boundaries are strictly between consecutive centroids.
    3. MSE matches theoretical Max-Lloyd optimum within 10%.
    """
    # 1. Sorted centroids
    assert np.all(np.diff(cb.centroids) > 0), f"Centroids not sorted for b={b}, d={d}"

    # 2. Boundaries between centroids
    for i, bnd in enumerate(cb.boundaries):
        assert cb.centroids[i] < bnd < cb.centroids[i + 1], \
            f"Boundary {i} out of range for b={b}, d={d}"

    # 3. MSE sanity: must be lower than uniform quantization of same range
    rng = np.random.RandomState(99)
    from turboquant import _beta_samples, polarquant_encode, polarquant_decode
    samples = _beta_samples(d, n_samples=n_val, rng=rng)
    indices = polarquant_encode(samples[None], cb)[0]
    recon = polarquant_decode(indices[None], cb)[0]
    mse = np.mean((samples - recon) ** 2)

    # Max-Lloyd should be better than or comparable to uniform quantization
    # of the sample range. For a concentrated Beta distribution the mass outside
    # the centroid range is negligible, so we compare against the sample std dev
    # as a simple sanity bound: MSE must be < variance / n_levels.
    sample_var = np.var(samples)
    n_levels = 2 ** b
    # A very loose upper bound: Lloyd-Max MSE < sample variance / n_levels
    bound = sample_var / n_levels * 4  # factor 4: generous for non-uniform distributions
    assert mse < bound, \
        f"Max-Lloyd MSE {mse:.6f} too large (bound={bound:.6f}) for b={b}, d={d}"

    print(f"  VALID b={b} d={d}: MSE={mse:.7f}  (bound={bound:.7f})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating codebooks: b∈{args.b}, d∈{args.d}, n_samples={args.n_samples:,}")
    print()

    codebooks: dict = {}
    tables: dict = {}  # for .npz output

    for d in args.d:
        for b in args.b:
            print(f"  Computing b={b}, d={d} ...", end="", flush=True)
            cb = build_codebook(b=b, d=d, n_samples=args.n_samples)
            codebooks[(b, d)] = cb
            tables[f"centroids_b{b}_d{d}"] = cb.centroids
            tables[f"boundaries_b{b}_d{d}"] = cb.boundaries
            print(f" done  ({2**b} levels, centroid range [{cb.centroids[0]:.4f}, {cb.centroids[-1]:.4f}])")

    # Write C header
    header_path = out_dir / "codebooks.h"
    header_content = generate_header(codebooks, n_samples=args.n_samples)
    header_path.write_text(header_content)
    print(f"\nWrote C header → {header_path}")

    # Write NumPy archive
    npz_path = Path("codebook_tables.npz")
    np.savez(str(npz_path), **tables)
    print(f"Wrote NumPy archive → {npz_path}")

    # Optional validation
    if args.validate:
        print("\nValidating codebooks...")
        for (b, d), cb in codebooks.items():
            validate_codebook(cb, b=b, d=d)
        print("All codebooks validated.")

    print("\nDone. Include 'codebooks.h' in your TT-Metalium kernel build.")


if __name__ == "__main__":
    main()
